spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      security:
        protocol: PLAINTEXT
      auto:
        register:
          schemas: true
      schema:
        registry:
          url: http://localhost:8081